# Stage 1: Build dependencies
FROM python:3.14-slim AS builder
WORKDIR /app

# Install system dependencies for Postgres
RUN apt-get update && apt-get install -y gcc libpq-dev

# Copy the compiled requirements from the root (generated by 'make compile')
COPY requirements/ requirements/

# Install to the user directory to make copying to Stage 2 easier
RUN pip install --user --no-cache-dir -r requirements/base.txt -r requirements/dev.txt 

# Stage 2: Runtime
FROM python:3.14-slim
WORKDIR /app

# Install only the runtime library for postgres (keeps image small)
RUN apt-get update && apt-get install -y libpq5 && rm -rf /var/lib/apt/lists/*

# Copy installed packages from builder
COPY --from=builder /root/.local /root/.local
# Copy the rest of your application code
COPY . .

# Ensure scripts in .local/bin are usable
ENV PATH=/root/.local/bin:$PATH
ENV PYTHONUNBUFFERED=1

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]